- hosts: localhost
  vars_prompt:
    - name: "POSTGRESQL_LOGIN_HOST"
      prompt: "PostgreSQL Login Host"
      private: no
    - name: "POSTGRESQL_ADMIN_USER"
      prompt: "PostgreSQL Admin User"
      private: no
    - name: "POSTGRESQL_ADMIN_PW"
      prompt: "PostgreSQL Admin Password"
      private: yes
    - name: "DATABASE_NAME"
      prompt: "Name of the database and role you want to create"
      private: no
    - name: "ROLE_PASSWORD"
      prompt: "Password for the role"
      private: yes
  tasks:
  - name: Create Database
    postgresql_db:
      name: "{{ DATABASE_NAME }}"
      login_host: "{{ POSTGRESQL_LOGIN_HOST }}"
      login_user: "{{ POSTGRESQL_ADMIN_USER }}"
      login_password: "{{ POSTGRESQL_ADMIN_PW }}"
      ssl_mode: "require"

  - name: Revoke connect from public
    postgresql_privs:
      database: "{{ DATABASE_NAME }}"
      login_host: "{{ POSTGRESQL_LOGIN_HOST }}"
      login_user: "{{ POSTGRESQL_ADMIN_USER }}"
      login_password: "{{ POSTGRESQL_ADMIN_PW }}"
      roles: PUBLIC
      privs: CONNECT
      type: database

  - name: Create role
    postgresql_user:
      login_host: "{{ POSTGRESQL_LOGIN_HOST }}"
      login_user: "{{ POSTGRESQL_ADMIN_USER }}"
      login_password: "{{ POSTGRESQL_ADMIN_PW }}"
      db: "{{ DATABASE_NAME }}"
      name: "{{ DATABASE_NAME }}"
      password: "{{ ROLE_PASSWORD }}"
      expires: infinity
      conn_limit: 100
      priv: ALL
